version: '3'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:8080"
    networks:
      - fullcycle

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fullcycle

  app:
    build:
      context: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    volumes:
      - ./node:/usr/app
    networks:
      - fullcycle

networks:
  fullcycle:
    driver: bridge
